In [5]:
import numpy as np

In [8]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [10]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [12]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [15]:
# searchsorted =  jo b no. data hai wo kis position pe jayega
np.searchsorted(arr , 94)

12

In [16]:
arr1 = np.array([0,345,454,0,0,0,0,0,0])

In [18]:
# count non-zero elementes
np.count_nonzero(arr1)

2

In [19]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [72]:
# > jo b data 6 se jyada hai uska index nikal kr dega

In [73]:
np.where(arr > 6)

(array([0, 5, 8]),)

In [24]:
'''extract()  = condition ko satisfy krne vale data ko nikalta hai'''

'extract()  = condition ko satisfy krne vale data ko nikalta hai'

In [25]:
np.extract(arr >3 , arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [27]:
# numpy - byte swapping
'''ele ka byte nikalta hai'''

'ele ka byte nikalta hai'

In [29]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [45]:
# Numpy - copies & views
''' view()  == svelo copy
    copy() == deep copy'''

' view()  == svelo copy\n    copy() == deep copy'

In [31]:
arr 

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [44]:
a = np.copy(arr)     # deep copy

In [33]:
a[0] = 20

In [34]:
a

array([ 20,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [35]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [42]:
b = arr.view()       # svelo copy 

In [37]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [38]:
b[0] = 67

In [39]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [40]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [46]:
# Numpy - matrix library

In [56]:
import numpy.matlib as nm

In [58]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [59]:
nm.ones((2,3))

matrix([[1., 1., 1.],
        [1., 1., 1.]])

In [60]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [61]:
# numpy - liner Algebra

In [62]:
arr1 = np.random.randint([[2,3],[4,5]])

In [63]:
arr2 = np.random.randint([[2,3],[4,5]])

In [68]:
# matrix multiplication
np.dot(arr1,arr2)

array([[1, 1],
       [6, 0]])

In [67]:
# matrix multiplication
arr1@arr2

array([[1, 1],
       [6, 0]])