In [7]:
'''Numpy - numerical python

numpy array and matrix k sath deal krta hai'''

'Numpy - numerical python\n\nnumpy array and matrix k sath deal krta hai'

In [8]:
''' numpy mai array = super class
              matrix = sub class'''

' numpy mai array = super class\n              matrix = sub class'

In [9]:
''' numpy.array()   ==  numpy.asarray   == asanyarray() ==  list ko array mai convert krna hai'''

' numpy.array()   ==  numpy.asarray   == asanyarray() ==  list ko array mai convert krna hai'

In [10]:
import numpy

In [11]:
l = [1,2,3,4]

In [12]:
ar = numpy.array(l)

In [13]:
ar

array([1, 2, 3, 4])

In [14]:
type(ar)               # ndarray  =  n diamensional array

numpy.ndarray

In [15]:
# 1d array = single list pass = iska coordinate system mai represent sirf x axis pr hoga
numpy.array([1,2,3,4])

array([1, 2, 3, 4])

In [16]:
#2d array = single list k andar multiple list pass kroge 
# iska coordinate system mai represent =  default index ko dekr y axis and x axis pr hoga
numpy.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [17]:
numpy.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [18]:
a = [2,3,4]

In [19]:
numpy.asanyarray(a)

array([2, 3, 4])

In [20]:
'''matrix() = bydefault 2d array hota hai'''

'matrix() = bydefault 2d array hota hai'

In [21]:
m = numpy.matrix([1,2,3,4])   # 2 list so 2 daimensional

In [22]:
''' yha pe asanyarray matrix ko array mai convert nahi krega 
kyoki matrix 2d array hi hai'''
numpy.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [23]:
m = numpy.array([1,2,3,4,5,6])

In [24]:
n = m

In [25]:
n

array([1, 2, 3, 4, 5, 6])

In [26]:
n[0]

1

In [27]:
n[0] = 100

In [28]:
n

array([100,   2,   3,   4,   5,   6])

In [29]:
m

array([100,   2,   3,   4,   5,   6])

In [30]:
'''m = array 
   n = m       jo b change kro ge usko m ,n dono se updated array le paoge'''

'''svelo copy = same location pr data ko copy kr rhe ho 
(alag location pr store nahi kr rhe ho) 
so jo b variable usko access krta hai wo usko manipulate b kr skega'''

'svelo copy = same location pr data ko copy kr rhe ho \n(alag location pr store nahi kr rhe ho) \nso jo b variable usko access krta hai wo usko manipulate b kr skega'

In [31]:
'''deep copy = different location pe copy ko store kr rha he 
so perticular variable se perticular changes ko access kr skte ho'''

d = numpy.copy(m)

In [32]:
d

array([100,   2,   3,   4,   5,   6])

In [33]:
m

array([100,   2,   3,   4,   5,   6])

In [34]:
m[1] = 20

In [35]:
m

array([100,  20,   3,   4,   5,   6])

In [36]:
d

array([100,   2,   3,   4,   5,   6])

In [37]:
'''fromfunction() = diff-diff daimentional ka array generate krna''' 

'fromfunction() = diff-diff daimentional ka array generate krna'

In [38]:
numpy.fromfunction(lambda i,j : i==j , (5,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [39]:
numpy.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [40]:
numpy.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [41]:
'''fromiter(iterable variable  ,  dtype) 
 
   fromstring(string  ,  sep = 'string ko aap kis se tod na chahte ho')'''

"fromiter(iterable variable  ,  dtype) \n \n   fromstring(string  ,  sep = 'string ko aap kis se tod na chahte ho')"

In [42]:
iterable = [i*i for i in range(5)]

In [43]:
numpy.fromiter(iterable,int)          # generating array

array([ 0,  1,  4,  9, 16])

In [44]:
numpy.fromstring('12 , 15' , sep = ',' )       # generating array

array([12., 15.])

In [45]:
# numpy - data type

''' arr.ndim   =   diamention kitna hai
    arr.size   =   kitne eles hai
    shape      =  n , m 
    dtypes     =   datatypes 
    '''

' arr.ndim   =   diamention kitna hai\n    arr.size   =   kitne eles hai\n    shape      =  n , m \n    dtypes     =   datatypes \n    '

In [46]:
l = [1,2,3,4,5,6]

In [47]:
ar = numpy.array(l)

In [48]:
ar

array([1, 2, 3, 4, 5, 6])

In [49]:
# array ka daimentional 
ar.ndim

1

In [50]:
ar2 = numpy.array([[1,2,6],[3,4,5]])

In [51]:
ar2.ndim

2

In [52]:
ar2.size

6

In [53]:
ar2.shape

(2, 3)

In [54]:
ar2

array([[1, 2, 6],
       [3, 4, 5]])

In [55]:
ar2.dtype

dtype('int64')

In [56]:
list(range(5))

[0, 1, 2, 3, 4]

In [68]:
'''array ko autometic generate
numpy.arange(start,end,jump) = floating value b dal skte hai '''

'array ko autometic generate\nnumpy.arange(start,end,jump) = floating value b dal skte hai '

In [61]:
numpy.arange(2.3,5.6,0.5)

array([2.3, 2.8, 3.3, 3.8, 4.3, 4.8, 5.3])

In [64]:
list(numpy.arange(2.3,5.6,0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [70]:
'''linspace()  = para ye dono k bich k itne data generate kro'''

'linspace()  = para ye dono k bich k itne data generate kro'

In [69]:
numpy.linspace(10,15,10)

array([10.        , 10.55555556, 11.11111111, 11.66666667, 12.22222222,
       12.77777778, 13.33333333, 13.88888889, 14.44444444, 15.        ])

In [79]:
'''.zero()  =  zero array'''

'.zero()  =  zero array'

In [71]:
numpy.zeros(4)    # 1d

array([0., 0., 0., 0.])

In [77]:
numpy.zeros((4,5))           # 2d ((row,col))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
numpy.zeros((3,4,2))           # 3d ((size , row , col))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [87]:


''' 3 rows
    6 cols
2*3*2 size'''

numpy.zeros((2,3,2,3,6))

array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]],



       [[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],



In [89]:
numpy.zeros((2,3,2,3,6)).ndim    # 5d array

5

In [96]:
''' till 3d hi aap visulization kr skte ho'''

' till 3d hi aap visulization kr skte ho'

In [126]:
'''.ones()  =  sare ele ki value 1 array'''

'.ones()  =  sare ele ki value 1 array'

In [97]:
numpy.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [98]:
numpy.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [99]:
numpy.ones((3,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [100]:
on = numpy.ones((3,4))

In [101]:
on + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [102]:
on * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [104]:
on + 5

array([[0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5]])

In [105]:
on / 5

array([[0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2]])

In [124]:
'''empty array'''
numpy.empty((3,7))

array([[4.67548857e-310, 6.94348129e-310, 6.94348316e-310,
        6.94348326e-310, 6.94348129e-310, 6.94348232e-310,
        6.94348240e-310],
       [6.94348226e-310, 6.94348204e-310, 6.94348129e-310,
        6.94348306e-310, 6.94348331e-310, 6.94348129e-310,
        6.94348129e-310],
       [6.94348129e-310, 6.94348130e-310, 6.94348326e-310,
        2.42092166e-322, 4.67604602e-310, 6.94348359e-310,
        1.02765654e-321]])

In [129]:
''' eye()  =  identity matrix'''

' eye()  =  identity matrix'

In [127]:
numpy.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [134]:
# 2 and 4 li line ko leke use 20 se divide kr dega
numpy.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [137]:
'''same as linspace diff = ye log nikal k dega'''
numpy.logspace(2,4,20 , base =2 )

array([ 4.        ,  4.30276234,  4.62844095,  4.97877036,  5.3556164 ,
        5.76098615,  6.19703857,  6.66609605,  7.17065677,  7.71340798,
        8.29724036,  8.92526334,  9.60082176, 10.32751358, 11.10920914,
       11.95007169, 12.85457963, 13.82755029, 14.87416568, 16.        ])

In [147]:
''' random.randn(row , col)  =  random data generate krna

standard normal distribution jis ka mean = 0 , std = 1 hoga
      
      
        '''

' random.randn(row , col)  =  random data generate krna\n\nstandard normal distribution jis ka mean = 0 , std = 1 hoga\n      \n      \n        '

In [148]:
'''random data generate'''
arr1 =  numpy.random.randn(3,4)

In [149]:
import pandas 

In [146]:
pandas.DataFrame(arr1)

0         1         2         3
0  1.873835 -1.181662 -0.905330  0.014147
1  0.982561  0.809462 -0.000131 -0.084266
2 -0.310180  0.132293  0.868075 -0.680683

In [154]:
'''randint(start,end,(row,col))  = random interer generate'''

'randint(start,end,(row,col))  = random interer generate'

In [157]:
pandas.DataFrame(numpy.random.randint(1,110,(300,400))).to_csv('test.csv')

In [160]:
ar = numpy.random.rand(3,4)

In [161]:
ar

array([[0.13746016, 0.44875745, 0.65229241, 0.64298874],
       [0.48526759, 0.67427074, 0.58898729, 0.24214529],
       [0.2206136 , 0.24542818, 0.58242616, 0.38922254]])

In [162]:
'''reshape(row,col)  = array ka shape change krna'''

'reshape(row,col)  = array ka shape change krna'

In [169]:
ar.reshape(4,3)

array([[0.13746016, 0.44875745, 0.65229241],
       [0.64298874, 0.48526759, 0.67427074],
       [0.58898729, 0.24214529, 0.2206136 ],
       [0.24542818, 0.58242616, 0.38922254]])

In [173]:
ar1 = ar.reshape(4,3)

In [174]:
# indexing and slicing 

In [176]:
ar1[2][2]

0.22061360263945673

In [178]:
ar1[1:4]

array([[0.64298874, 0.48526759, 0.67427074],
       [0.58898729, 0.24214529, 0.2206136 ],
       [0.24542818, 0.58242616, 0.38922254]])

In [181]:
ar1[1:4,2]

array([0.67427074, 0.2206136 , 0.38922254])

In [182]:
ar1

array([[0.13746016, 0.44875745, 0.65229241],
       [0.64298874, 0.48526759, 0.67427074],
       [0.58898729, 0.24214529, 0.2206136 ],
       [0.24542818, 0.58242616, 0.38922254]])

In [185]:
ar1[1:3,1]

array([0.48526759, 0.24214529])

In [186]:
numpy.random.randint(1,100,(5,5))

array([[ 1, 63, 41, 40, 87],
       [23, 46, 37, 55, 46],
       [91,  5, 99, 73, 38],
       [23, 12, 11, 19,  7],
       [20, 70, 11, 27, 91]])

In [197]:
arr = numpy.random.randint(1,100,(5,5))

In [200]:
'''sirf vahi data nikal k do jo 50 > ho'''
arr[arr > 50]

array([58, 94, 53, 66, 87, 65, 55, 52, 80, 84, 77])

In [201]:
arr[arr > 90]

array([94])

In [202]:
arr

array([[12, 16, 13, 22, 58],
       [94, 53, 38, 46, 40],
       [37, 16, 15, 66, 87],
       [65, 55, 52, 20, 80],
       [ 5, 34, 14, 84, 77]])

In [203]:
arr[2:4]

array([[37, 16, 15, 66, 87],
       [65, 55, 52, 20, 80]])

In [209]:
arr[2:4,[1,2]]    # slicing and indexing

array([[16, 15],
       [55, 52]])

In [210]:
arr[0:2,[2,3]]

array([[13, 22],
       [38, 46]])

In [214]:
arr[0][0] = 5000   # manipulate

In [215]:
arr

array([[5000,   16,   13,   22,   58],
       [  94,   53,   38,   46,   40],
       [  37,   16,   15,   66,   87],
       [  65,   55,   52,   20,   80],
       [   5,   34,   14,   84,   77]])

In [216]:
arr1 = numpy.random.randint(1,3,[3,3])

In [217]:
arr2 = numpy.random.randint(1,2,[3,3])

In [218]:
arr1

array([[2, 2, 1],
       [2, 2, 2],
       [1, 2, 1]])

In [219]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [222]:
arr1 + arr2    # sum

array([[3, 3, 2],
       [3, 3, 3],
       [2, 3, 2]])

In [231]:
arr1 - arr2    # simple multiplication

array([[1, 1, 0],
       [1, 1, 1],
       [0, 1, 0]])

In [232]:
arr1 / arr2

array([[2., 2., 1.],
       [2., 2., 2.],
       [1., 2., 1.]])

In [233]:
arr1 * arr2

array([[2, 2, 1],
       [2, 2, 2],
       [1, 2, 1]])

In [234]:
# matrix multiplication
arr1@arr2

array([[5, 5, 5],
       [6, 6, 6],
       [4, 4, 4]])

In [236]:
# arr1 / 0 = inf aayega

In [237]:
arr1 / 0

/tmp/ipykernel_84/824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [239]:
arr1 + 100

array([[102, 102, 101],
       [102, 102, 102],
       [101, 102, 101]])

In [240]:
arr1**2

array([[4, 4, 1],
       [4, 4, 4],
       [1, 4, 1]])

In [264]:
# Broadcasting

'''liner array(row) ko zero array mai row by row add krta hai'''

'liner array(row) ko zero array mai row by row add krta hai'

In [249]:
 numpy.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [250]:
 numpy.array([1,2,3,4])

array([1, 2, 3, 4])

In [251]:
a1 = numpy.zeros((4,4))

In [255]:
row = numpy.array([1,2,3,4])

In [256]:
a1 + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [265]:
'''column by column add krna hai

liner ki jagh(row ki jagh ) 2d arr bnao and .T (transpose krdo ) then add'''

'column by column add krna hai\n\nliner ki jagh(row ki jagh ) 2d arr bnao and .T (transpose krdo ) then add'

In [257]:
row.T

array([1, 2, 3, 4])

In [258]:
col = numpy.array([[1,2,3,4]])    # 2d array

In [260]:
col.T                             # transpose

array([[1],
       [2],
       [3],
       [4]])

In [266]:
a1 + col.T                       # transpose ko add

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [268]:
arr1 = numpy.random.randint(1,4,(3,4))

In [269]:
#squar nikalna
numpy.sqrt(arr1)

array([[1.41421356, 1.73205081, 1.73205081, 1.        ],
       [1.        , 1.73205081, 1.        , 1.        ],
       [1.41421356, 1.        , 1.41421356, 1.73205081]])

In [271]:
#exponant nikalo
numpy.exp(arr1)

array([[ 7.3890561 , 20.08553692, 20.08553692,  2.71828183],
       [ 2.71828183, 20.08553692,  2.71828183,  2.71828183],
       [ 7.3890561 ,  2.71828183,  7.3890561 , 20.08553692]])

In [272]:
numpy.log10(arr1)

array([[0.30103   , 0.47712125, 0.47712125, 0.        ],
       [0.        , 0.47712125, 0.        , 0.        ],
       [0.30103   , 0.        , 0.30103   , 0.47712125]])