In [1]:
#array manipulation

In [7]:
import numpy as np

In [9]:
arr = np.random.randint(1,10,(3,4))

In [10]:
arr

array([[5, 4, 3, 4],
       [3, 4, 6, 5],
       [5, 3, 5, 9]])

In [11]:
arr.reshape(6,2)

array([[5, 4],
       [3, 4],
       [3, 4],
       [6, 5],
       [5, 3],
       [5, 9]])

In [12]:
arr.reshape(2,6)

array([[5, 4, 3, 4, 3, 4],
       [6, 5, 5, 3, 5, 9]])

In [17]:
# array transpose
arr.T

array([[5, 3, 5],
       [4, 4, 3],
       [3, 6, 5],
       [4, 5, 9]])

In [18]:
arr

array([[5, 4, 3, 4],
       [3, 4, 6, 5],
       [5, 3, 5, 9]])

In [21]:
#flatten() =  2d array ko 1d array mai convert
arr.flatten()

array([5, 4, 3, 4, 3, 4, 6, 5, 5, 3, 5, 9])

In [22]:
arr1 = np.array([1,2,3,4])

In [23]:
arr1.ndim

1

In [25]:
# expand_dims(array_name , axis = 1)  = 1d array ko 2d mai convert
np.expand_dims(arr1 , axis = 1)     # column k accross

array([[1],
       [2],
       [3],
       [4]])

In [27]:
np.expand_dims(arr1 , axis = 0)        # row k accross

array([[1, 2, 3, 4]])

In [28]:
arr

array([[5, 4, 3, 4],
       [3, 4, 6, 5],
       [5, 3, 5, 9]])

In [30]:
'''squeeze()   = list k andar multiple list , each k andar 1- 1 ele

tab ye usko single list mai lake dega'''

'squeeze()   = list k andar multiple list , each k andar 1- 1 ele\n\ntab ye usko single list mai lake dega'

In [34]:
 np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [35]:
 data = np.array([[1],[2],[3]])

In [36]:
np.squeeze(data)

array([1, 2, 3])

In [37]:
arr1

array([1, 2, 3, 4])

In [39]:
'''repeat(array , number (how many time you want to repeat)) 

array elements ko repeat krna'''

'repeat(array , number (how many time you want to repeat)) \n\narray elements ko repeat krna'

In [38]:
np.repeat(arr1 , 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [43]:
'''roll(array , shif number)   = array k eles ko ghumata hai base on shif number'''

'roll(array , shif number)   = array k eles ko ghumata hai base on shif number'

In [42]:
np.roll(arr1 , 2)

array([3, 4, 1, 2])

In [46]:
'''diag(1d array_name) = 2d array return krega jo b 1d array dalte ho sko diagonal mai layega'''

'diag(1d array_name) = 2d array return krega jo b 1d array dalte ho sko diagonal mai layega'

In [44]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [47]:
# numpy = binary operations

In [48]:
arr1 = np.random.randint(1,10,(3,4))

In [49]:
arr2 = np.random.randint(1,10,(3,4))

In [50]:
arr1

array([[8, 9, 6, 4],
       [1, 8, 3, 5],
       [1, 9, 6, 1]])

In [51]:
arr2

array([[6, 2, 7, 4],
       [6, 6, 7, 1],
       [4, 6, 2, 6]])

In [52]:
arr1 + arr2

array([[14, 11, 13,  8],
       [ 7, 14, 10,  6],
       [ 5, 15,  8,  7]])

In [53]:
arr1 * arr2

array([[48, 18, 42, 16],
       [ 6, 48, 21,  5],
       [ 4, 54, 12,  6]])

In [54]:
arr1 / arr2

array([[1.33333333, 4.5       , 0.85714286, 1.        ],
       [0.16666667, 1.33333333, 0.42857143, 5.        ],
       [0.25      , 1.5       , 3.        , 0.16666667]])

In [55]:
arr1 - arr2

array([[ 2,  7, -1,  0],
       [-5,  2, -4,  4],
       [-3,  3,  4, -5]])

In [56]:
#reminder operation
arr1%arr2

array([[2, 1, 6, 0],
       [1, 2, 3, 0],
       [1, 3, 0, 1]])

In [58]:
# power operation
arr1 ** arr2

array([[262144,     81, 279936,    256],
       [     1, 262144,   2187,      5],
       [     1, 531441,     36,      1]])

In [61]:
# and operation
arr1 & arr2

array([[0, 0, 6, 4],
       [0, 0, 3, 1],
       [0, 0, 2, 0]])

## 

In [69]:
'''niget operation  =    ~   

value mai + 1 
sign ko - krta hai'''

'niget operation  =    ~   \n\nvalue mai + 1 \nsign ko - krta hai'

In [67]:
~arr1

array([[ -9, -10,  -7,  -5],
       [ -2,  -9,  -4,  -6],
       [ -2, -10,  -7,  -2]])

In [68]:
arr1

array([[8, 9, 6, 4],
       [1, 8, 3, 5],
       [1, 9, 6, 1]])

In [71]:
# or operation
arr1|arr2

array([[14, 11,  7,  4],
       [ 7, 14,  7,  5],
       [ 5, 15,  6,  7]])

In [73]:
# grater than operation
arr1 > arr2

array([[ True,  True, False, False],
       [False,  True, False,  True],
       [False,  True,  True, False]])

In [75]:
# numpy - string functions

In [77]:
arr =np.array(['mira','kumar'])

In [78]:
np.char.upper(arr)

array(['MIRA', 'KUMAR'], dtype='<U5')

In [79]:
np.char.title(arr)

array(['Mira', 'Kumar'], dtype='<U5')

In [80]:
np.char.capitalize(arr)

array(['Mira', 'Kumar'], dtype='<U5')

In [81]:
# numpy - mathemetical functions

In [82]:
arr1

array([[8, 9, 6, 4],
       [1, 8, 3, 5],
       [1, 9, 6, 1]])

In [83]:
np.sin(arr1)

array([[ 0.98935825,  0.41211849, -0.2794155 , -0.7568025 ],
       [ 0.84147098,  0.98935825,  0.14112001, -0.95892427],
       [ 0.84147098,  0.41211849, -0.2794155 ,  0.84147098]])

In [84]:
np.cos(arr1)

array([[-0.14550003, -0.91113026,  0.96017029, -0.65364362],
       [ 0.54030231, -0.14550003, -0.9899925 ,  0.28366219],
       [ 0.54030231, -0.91113026,  0.96017029,  0.54030231]])

In [85]:
np.tan(arr1)

array([[-6.79971146, -0.45231566, -0.29100619,  1.15782128],
       [ 1.55740772, -6.79971146, -0.14254654, -3.38051501],
       [ 1.55740772, -0.45231566, -0.29100619,  1.55740772]])

In [86]:
np.tanh(arr1)

array([[0.99999977, 0.99999997, 0.99998771, 0.9993293 ],
       [0.76159416, 0.99999977, 0.99505475, 0.9999092 ],
       [0.76159416, 0.99999997, 0.99998771, 0.76159416]])

In [88]:
np.log10(arr1)

array([[0.90308999, 0.95424251, 0.77815125, 0.60205999],
       [0.        , 0.90308999, 0.47712125, 0.69897   ],
       [0.        , 0.95424251, 0.77815125, 0.        ]])

In [89]:
np.exp(arr1)

array([[2.98095799e+03, 8.10308393e+03, 4.03428793e+02, 5.45981500e+01],
       [2.71828183e+00, 2.98095799e+03, 2.00855369e+01, 1.48413159e+02],
       [2.71828183e+00, 8.10308393e+03, 4.03428793e+02, 2.71828183e+00]])

In [90]:
np.sqrt(arr1)

array([[2.82842712, 3.        , 2.44948974, 2.        ],
       [1.        , 2.82842712, 1.73205081, 2.23606798],
       [1.        , 3.        , 2.44948974, 1.        ]])

In [93]:
np.power(arr1 , 2)

array([[64, 81, 36, 16],
       [ 1, 64,  9, 25],
       [ 1, 81, 36,  1]])

In [94]:
np.mean(arr1)

5.083333333333333

In [97]:
np.median(arr1)

5.5

In [98]:
np.std(arr1)

2.9568658332016953

In [100]:
np.var(arr1)

8.743055555555555

In [101]:
np.min(arr1)

1

In [102]:
np.max(arr1)

9